theme: jekyll-theme-cayman
title: [Tiny Systems Group]
description: [Software/Hardware for Tiny Embedded Systems]
menu:
  items:
    - text: Home
      url: README.html
    - text: Members
      url: Members.md
    - text: Publications
      url: Publications.md
    - text: Projects
      url: Projects.md
